---
name: Build and publish
on:
  push:
    tags:
      - v*
env:
  PROJECT_PATH: TlsVersionCheck/TlsVersionCheck.csproj
  RELEASE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json
jobs:
  build:
    name: Deploy
    runs-on: windows-latest
    steps:
      - name: Get version
        id: version
        uses: battila7/get-version-action@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore packages
        run: dotnet restore ${{ env.PROJECT_PATH }}
      - name: Publish single executable
        run: dotnet publish ${{ env.PROJECT_PATH }} --no-restore --configuration Release -r win-x64 /p:PublishSingleFile=true --output ${{env.RELEASE_OUTPUT_DIRECTORY }}
      - name: Upload the binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TlsVersionCheck.exe
          path: ${{ env.RELEASE_OUTPUT_DIRECTORY }}
  create-release:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v ${{ version }}
          release_name: Release V ${{ version }}
          draft: false
          prerelease: false
          asset_upload: ${{ env.RELEASE_OUTPUT_DIRECTORY }}